credentials:
  usernames:
    alvaro:
      name: Alvaro Herrera
      password: e1eab1822d8962634607c2415649ecce   # tu hash aquí

    maru:
      name: Maru Rodríguez
      password: d671b0b633763954ffda9dc3300dbb3f   # segundo hash

    carlos:
      name: Johanna
      password: 38e578279a32a446f5fd58f200bcb97e   # tercer hash

cookie:
  name: inventario_cookie
  key: 893bf1b7b92e4b7b8d7643b5e22a3e1b  # puedes usar uuid4 si quieres
  expiry_days: 7


